### ISSUE TITLE
[request] Possible Light and dark theme?

### ISSUE THREAD

**Issue by vnl** [YOUSSSOF/Movies-App#1]
Amazing app and learning a lot from it. 

Would it be possible to add theming to the application (light and dark) and perhaps the [material 3 theming](https://github.com/flutter/samples/tree/main/material_3_demo)

**Comment by YOUSSSOF** [comment]
Thank my friend, I'm glad you enjoyed it. 
For now unfortunately it's not possible, but you can try your own chance for theming :)
